# Generated by Django 5.0.2 on 2024-03-30 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='site_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='apps.sitesettings'),
            preserve_default=False,
        ),
    ]
